---
title: "Do researchers preferentially collaborate with colleagues of the same gender?"
author:
- Luke Holman* and Claire Morandin\textsuperscript{ยง}
- '*\textit{luke.holman@unimelb.edu.au}'
- \textsuperscript{ยง}\textit{claire.morandin@helsinki.fi} \vspace{5mm}
bibliography: references.bib
output:
  pdf_document: default
  html_document: default
  word_document: default
fontsize: 12pt
header-includes: \usepackage{microtype} \usepackage[all]{hypcap} \usepackage{amsmath}
  \usepackage{booktabs} \usepackage{caption} \usepackage[labelfont=bf]{caption} \usepackage{titling}
  \pretitle{\begin{flushleft}\LARGE} \posttitle{\par\end{flushleft}\vskip 0.5em} \preauthor{\begin{flushleft}\large
  \lineskip 0.5em} \postauthor{\par\end{flushleft}} \predate{\begin{flushleft}\large}
  \postdate{\par\end{flushleft}} \usepackage{fancyhdr} \pagestyle{fancy} \fancyhead[LO,LE]{\textsl{\leftmark}}
  \rhead[]{Gender and coauthorship} \usepackage[noabbrev,capitalise]{cleveref} \usepackage{titlefoot}
  \usepackage{amssymb} \usepackage{rotating} \usepackage{lineno} \linenumbers
csl: plos.csl
abstract: Evidence suggests that women in academia are hindered by conscious and unconscious
  biases, and often feel excluded from formal and informal opportunities for research
  collaboration. In addition to ensuring fairness and helping to redress gender imbalance
  in the academic workforce, increasing women's access to collaboration could help
  scientific progress by drawing on more of the available human capital. Here, we
  test whether researchers preferentially collaborate with same-gendered colleagues,
  using more stringent methods and a larger dataset than in past work. Our results
  reaffirm that researchers co-publish with colleagues of the same gender, and show
  that this 'gender homophily' is slightly stronger today than it was 10 years ago.
  Contrary to our expectations, we found no evidence that homophily is driven mostly
  by senior academics, and no evidence that homophily is strongest in fields where
  women are in the minority. Interestingly, journals with a high impact factor for their discipline tended to have comparatively low homophily, as predicted if mixed-gender teams produce better research.
  We discuss potential causes of gender homophily in science. \vspace{5mm} \par\noindent
  \textbf{Keywords:} Gender bias, Homophily, Scientific collaboration, Text mining,
  Women in STEM. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load some little files with numbers to be inserted into the MS
sample.size <- read.csv("sample.size.table.csv", stringsAsFactors = FALSE)
sample.size[,2] <- prettyNum(sample.size[,2], big.mark = ",")
sample.size[,3] <- prettyNum(sample.size[,3], big.mark = ",")
names(sample.size)[2:3] <- c("n2005", "n2015")

fig2 <- readRDS("fig2_numbers.RData") # For figure 2
n.journals <- fig2[1]
n.sig.homo <- fig2[2]
n.sig.hetero <- fig2[3]

R2 <- readRDS("R2_for_figure4.RData") # For Fig 4
```

\maketitle\unmarkedfntext{*School of BioSciences, The University of Melbourne, Victoria, Australia.}
\maketitle\unmarkedfntext{\textsuperscript{ยง}Organismal and Evolutionary Biology Research Programme,
Faculty of Biological and Environmental Sciences, University of Helsinki, Finland.}

\newpage
# Introduction

Women are severely underrepresented in many branches of science, technology, engineering, mathematics, and medicine (STEMM), and face additional challenges and inequities relative to men [e.g. @Shaw_2012; @Lariviere_2013; @West_2013; @Elsevier_report; @Holman_2018]. On average, women occupy more junior positions [@Wutte_2007; @Reuben_2014] with lower salaries [@Trower_2002; @Umbach_2007], receive less grant money [@Hosek_2005; @pohlhaus_2011], are promoted more slowly [@Zuckerman_1987; @Rosenfeld_1991; @Long_1993; @Hopkins_2013], and are allocated fewer resources [@ODorchai_2009] and less research funding [@Feldt_1986; @Stack_2004; @Lariviere_2011]. Experimental evidence suggests that bias against women plays a major role in generating these differences [@Moss_2012; @Knobloch_2013].

Because publishing, networking and collaboration are instrumental to scientific productivity and academic career advancement [@Lee_2005; @Wuchty_2007; @Abramo_2009; @Lariviere_2015], dozens of studies have tested for gender differences in these areas [e.g. @Long_1992; @Bozeman_2011; @Abramo_2013; @Badar_2013; references in Table S1 of @Holman_2018]. For example, studies have found that women tend to be less involved in international collaboration [@Lewison_2001; @Webster_2001; @Bozeman_2004; @Lariviere_2011; @Abramo_2013], collaborate less within their own university departments [@Webster_2001], have less prestigious collaborations [@Long_1990], and fewer collaborations in total [@Fuchs_2001]. These gender differences in collaboration practice presumably have multiple causes, which might include implicit and explicit gender bias [@Moss_2012], differential family obligations [@Reskin_1978; @Long_1990; @Wright_2003], gender differences in confidence or self-esteem [@bleidorn2016age], concerns relating to sexual harassment [@jagsi_2016], and unequal access to conferences [@Martin_2014] and travel funds [@Bozeman_2004].

A high, steadily increasing proportion of research papers is written by more than one author [@West_2013], making collaboration a key predictor of publication output, and thus of career prospects [@Tower_2007; @Jordan_2008]. Additionally, empirical studies imply that mixed-gender or otherwise diverse teams produce better results on collaborative tasks than less diverse teams [@Britton_2000; @Reagans_2001; @Hong_2004; @Whittington_2008; @Bear_2011; @Herrera_2012; @Campbell_2013]. For reasons such as these, several studies have examined the author lists of published research articles in order to test for gender differences in collaboration frequency or pattern. To our knowledge, all of these studies imply that men co-publish with other men, and women with women, more often than expected if collaborators assort randomly with respect to gender [@Ferber_1980; @McDowell_1992; @Ghiasi_2015; @Crow_2015; @Fahmy_2017; @Zettler_2017; @Jadidi_2017; @Teele_2017; @Araujo_2017a; @Araujo_2017b]. This pattern of assortative publishing is often termed 'gender homophily'.

However, we believe that prior studies of gender homophily were hindered by a largely unacknowledged statistical issue that we name the Wahlund effect (\autoref{wahlund_plot}), by analogy with the conceptually similar Whalund effect in population genetics [@Wahlund_1928]. The Wahlund effect makes it deceptively difficult to infer gender-based preferences simply by counting the number of same- and mixed-gender coauthorships. Essentially, whenever coauthorship data are sampled from two or more discrete sets of literature, which vary in the author gender ratio and which are largely not connected by collaboration, the number of same-gendered coauthors will be inflated. This can give the impression that authors preferentially publish with same-gendered colleagues if no gender preferences exist, or even if opposite-gendered colleagues are preferred. For example, a sample of literature containing bioinformatics and cell biology papers will probably contain an excess of mostly-male and mostly-female author lists, simply because researchers preferentially work with colleagues from the same discipline, and because the author gender ratio is more male-biased in bioinformatics than in cell biology [@Holman_2018]. 

![The Wahlund effect can make it appear as if authors prefer to publish with same-gendered colleagues, even if no such preference exists. Here, coloured circles represent male and female authors, and coauthors are linked with lines. Across the whole set of ten papers, there is an apparent excess of same-gender collaborations: there are six same-gender papers and only four mixed-gender papers, which is fewer than the $10\times2\times0.5\times0.5 = 5$ mixed-gender papers expected under the null hypothesis that authors assort randomly with respect to gender. However, within each subset, there is no evidence that authors prefer to publish with same-gendered individuals (if anything, this small dataset suggests gender heterophily). The Wahlund effect will tend to inflate the frequency of same-sex coauthorships whenever the data is composed of two or more disconnected subsets of literature with different author gender ratios; these subsets could be research disciplines, older versus newer papers, or papers from authors in different countries. \label{wahlund_plot}](../figures/Figure 1 - Wahlund figure.pdf)

In the present study, we test whether life sciences researchers tend to co-publish with same-gendered colleagues, while controlling for the Wahlund effect as strictly as possible. We use a recently-published dataset describing the gender of 35.5m authors from 9.15m articles indexed on PubMed [@Holman_2018]. Holman et al. [-@Holman_2018] reported large differences in the gender ratio of authors across research disciplines, journals, countries, and across the years 2002-2016. We therefore tested for gender homophily while restricting our analysis to particular journals (i.e. research specialties), time periods, and countries. We quantified gender assortment using a metric called $\alpha'$ [@bergstrom_2016], which is positive when same-gender authors publish together more often than expected (gender homohily), negative when opposite-gender authors publish together more often than expected (heterophily), and equal to zero when authors assort randomly with respect to gender (see Methods).


# Results
## Gender homophily by discipline, time period, and authorship position
\autoref{alpha_histograms} shows the distribution of $\alpha'$ estimates in 2015-2016 across all journals for which we recovered sufficient data, when $\alpha'$ was calculated for all authors, first authors only, or last authors only. The great majority of journals had $\alpha' > 0$, and for many of these the FDR-corrected p-values suggested that $\alpha'$ was significantly greater than zero (1469/2077 journals were significant in 2015-16, and 404/1192 in 2005-6; S1 Data). Only 2/2077 journals had statistically significantly heterophily (i.e. $\alpha' < 0$) in 2015-16, and 1/1192 in 2005-6 (S2 Table). The remaining 606 or 787 journals (in 2015 and 2005 respectively) had a value of $\alpha'$ not significantly different from zero, consistent with the null hypothesis of random assortment with respect to gender.

![Of the `r n.journals` journals for which we had adequate data in 2015-2016, `r n.sig.homo` showed statistically significant evidence of gender homophily (denoted by $\alpha' > 0$), and `r n.sig.hetero` showed statistically significant evidence of heterophily ($\alpha' < 0$), after false discovery rate correction. The white area shows the number of journals for which homophily was significantly stronger than expected under the null hypothesis (p < 0.05), while the blue area shows all the remainder. Patterns were similar whether $\alpha'$ was calculated for all authors, for first authors only, or for last authors only. \label{alpha_histograms}](../figures/figure2.pdf)

$\alpha'$ was significantly higher in the literature sample from 2015-16 relative to 2005-6, though the difference in means was small (S1 Fig; Effect of the fixed factor 'Time period' in a linear mixed model of the data for all author positions: Cohen's $d$ = $0.091{\pm}0.04$, $t_{953}$ = 2.42, p = 0.016). 

When comparing pairs of $\alpha'$ values estimated for the first and last authors for the same journals, we found that $\alpha'$ tended to be higher for first authors than for last authors (S2 Fig; Effect of the fixed factor 'Authorship position' in a linear mixed model: Cohen's $d$ = $0.065{\pm}0.02$, $t_{2024}$ = 4.28, p < 0.0001). This suggests that the gender of the first author was a slightly stronger predictor of the remaining authors' genders than the gender of the last author, i.e. the opposite of what is predicted if senior scientists are causally responsible for homophily.

## Variance in homophily between disciplines
\autoref{alpha_histograms} illustrates the variance in journal homophily values ($\alpha'$) across scientific disciplines. All disciplines had a positive average $\alpha'$, although homophily appeared somewhat stronger in some disciplines than others (e.g. mean $\alpha'$ was $0.12{\pm}0.02$ for Urology journals and $0.03{\pm}0.01$ for Veterinary Medicine journals; \autoref{alpha_histograms}, S3 Table). However, there was no evidence for consistent differences in $\alpha'$ between disciplines: the random factor 'Discipline' explained around 1% of the variance in $\alpha'$ in the two linear mixed models described in the previous section (see \autoref{alpha_histograms} and mixed models in Online Supplementary Material). Thus, we cannot reject the null hypothesis that the processes causing positive $\alpha'$ are similarly strong in all the disciplines we examined.

There was no indication that journals publishing on a wide range of topics have higher $\alpha'$ values than more specialised journals, due to the Wahlund effect. For example, the journal category 'Multidisciplinary' -- which includes journals like _PLoS ONE_, _Nature_, _Science_, and _PNAS_ -- did not have notably elevated $\alpha'$ (\autoref{alpha_histograms}). This result suggests that our estimates of homophily, and estimates from some earlier studies, are not notably inflated by the presence of disparate research topics (with variable author gender ratios) being published within individual journals.

## Relationship between gender homophily and gender ratio
We next tested whether researchers are more or less likely to publish with same-gendered colleagues in strongly gender-biased disciplines (e.g. Surgery or Nursing), relative to disciplines with a comparatively gender-balanced workforce (e.g. Psychiatry). We found a positive, non-linear relationship between the overall gender ratio of all authors publishing in a particular journal [as estimated in @Holman_2018], and the estimated value of $\alpha'$ for all authors and for first authors (\autoref{alpha_gender_ratio}). Journals with a balanced or female-biased author gender ratio tended to have higher $\alpha'$ than journals with a male-biased author gender ratio (GAM smooth terms p < 0.001; Online Supplementary Material). The relationship was not statistically significant when $\alpha'$ was calculated for last authors (GAM, p = 0.142), though the trend appeared similar (\autoref{alpha_gender_ratio}).

![There is a weakly positive, non-linear relationship between the gender ratio of authors publishing in a journal, and the coefficient of homophily ($\alpha'$). Specifically, journals with 50% women authors or higher tended to have more same-sex coauthorships than did journals with predominantly men authors.  This relationship held whether $\alpha'$ was calculated for all authors, first authors only, or last authors only. A negative value on the x-axis denotes an excess of men authors, a positive value denotes an excess of women authors, and zero denotes gender parity. The lines were fitted using generalised additive models with the smoothing parameter $k$ set to 3. \label{alpha_gender_ratio}](../figures/figure3.pdf)

## Relationship between journal impact factor and gender homophily
We observed a noisy but statistically significant linear relationship between standardised journal impact factor and $\alpha'$, such that journals with a high impact factor for their discipline had weaker gender homophily than did journals with a low impact factor for their discipline (\autoref{impact_factor}; linear regression: $R^2$ = `r R2`, $t_{1415}$ = -8.0, p < 0.0001). 

![Journal impact factor (expressed relative to the average for the discipline) is negatively correlated with $\alpha'$. The relationship is noisy ($R^2$ = `r R2`), but the results suggest that journals with strong homophily tend to have lower impact factors than journals with weak homophily in the same discipline. \label{impact_factor}](../figures/figure4.pdf)

## Analysis accounting for differences in author gender ratio between countries
When we restricted the analysis by country, we observed statistically significant homophily for 72 of the 325 journal-country combinations tested (64 unique journals and 18 unique countries), and no significant evidence of heterophily (Figures S3-S4). Additionally, the values of $\alpha'$ calculated for each journal-country combination were mostly very similar to the $\alpha'$ values calculated for the journal as a whole (i.e. when pooling papers from different countries); on average, $\alpha'$ was only inflated in the main (non-country specific) analysis by 0.002 (S5 Fig). These results suggest that our findings of widespread homophily in the main analysis were not driven solely by a Wahlund effect resulting from gender differences between countries. 

## Theoretical expectations for $\alpha$ when the gender ratio differs between career stages
As shown in \autoref{simulation}, we predict that $\alpha$ is expected to be non-zero, even if collaborators are randomly selected with respect to gender, provided that there is a gender gap between career stages. The extent to which $\alpha$ deviates from zero depends on the relative frequencies of collaboration within and between career stages. When >50% of collaborations were between early and established researchers, we expect gender heterophily ($\alpha < 0$). Conversely, when >50% of collaborations occured within career stages, we expect gender homophily ($\alpha > 0$). In a few parameter spaces (shown in red; \autoref{simulation}), $\alpha$ was quite high, and overlapped with the values that we estimated (\autoref{alpha_histograms}).

![When there is a difference in gender ratio between early-career and established researchers, and collaboration is non-random with respect to career stage, the null expectation for $\alpha$ deviates from zero. An excess of collaborations between career stages gives the appearance of gender heterophily (lower rows, blue areas), while an excess of within-career stage collaborations produced apparent gender homophily (upper rows, red areas). However, the conditions required for strong gender homophily are quite restrictive, making it unlikely that this issue explains all of the homophily observed in Figure 2. Contour lines denote increments of 0.1. \label{simulation}](../figures/figure5 - Simulation.pdf)

Despite this overlap, \autoref{simulation} suggests that our main conclusions (and those of other studies of gender homophily) are probably robust to this career stage issue. We only expect strongly positive $\alpha$ when A) the gender ratio is highly skewed across career stages (e.g. a 5-fold difference), and B) collaborations between early and established researchers are very rare (e.g. <10% of the total). Both of these conditions are untrue for most fields: the gender gap across careers stages is generally less pronounced [e.g. @Shaw_2012; @Holman_2018], and it is very common for early-career researchers to co-publish with an established mentor [@macaluso_2016]. However, one can get $\alpha > 0$ for realistic combinations of parameters, e.g. a moderate shortage of women in senior positions coupled with a moderate excess of within-career stage collaboration, suggesting this effect might contribute to some of the observed homophily.

Lastly, we note that if there is a gender gap between career stages and coauthorships between early-career and established researchers comprise >50% of the total, then the baseline expectation for $\alpha$ is actually less than zero (blue areas in \autoref{simulation}). Therefore, our results might under-estimate the extent to which researchers preferentially select same-gendered collaborators in some cases.


# Discussion
We found evidence that researchers preferentially publish with same-gendered coauthors, even after implementing stringent controls for Wahlund effects (\autoref{wahlund_plot}). Our study therefore reaffirms earlier studies' conclusions [e.g. @Ferber_1980; @McDowell_1992; @Bentley_2003; @Crow_2015; @Ghiasi_2015; @Araujo_2017a; @Fahmy_2017; @Jadidi_2017; @Teele_2017; @Zettler_2017] and establishes their generality across the life sciences. Relatively few journals had $\alpha'$ values below zero, and almost no journals showed statistically significant gender heterophily after controlling for multiple testing. The excess of same-gender coauthorships was quite large: many journals had $\alpha' > 0.1$, indicating that the gender ratio of men's and women's coauthors differs by >10% in absolute terms. In relative terms, our findings are even more striking: for example, if men have 20% female coauthors and women have 30% (i.e. $\alpha' = 0.1$ for a field with a male-biased gender ratio), then women publish with women 50% more often than men do. 

An important limitation of our study is that we cannot reliably determine the cause(s) of the observed excess of same-gender coauthorships. As well as conscious or unconcious selection of collaborators based on gender, our results could be partly explained by uncontrolled Wahlund effects. However, we suspect the contribution of these to be minor, for four reasons: we found positive $\alpha'$ after controlling for three obvious sources of Wahlund effect; there was no inflation of $\alpha'$ in highly multidisciplinary journals; restricting the data by country yielded similar estimates of $\alpha'$; and we showed that differences in gender ratio between career stages are unlikely to fully explain our results. On balance, we believe the data provide good evidence that researchers preferentially select same-gendered collaborators, although the strength of this preference is uncertain.

We hypothesised that disciplines with a strongly skewed gender ratio might show the strongest gender homophily, e.g. because being in the minority might increase motivation to seek out same-gendered colleagues. Contrary to this hypothesis, we found no evidence that gender homophily is restricted to particular disciplines: $\alpha'$ was similarly high across the board (\autoref{alpha_histograms}). Moreover, $\alpha'$ was lower for journals with a male-biased author gender ratio relative to those with an even gender ratio. Interestingly, $\alpha'$ was highest in journals with a female-biased author gender ratio. This may suggest that men are more likely to preferentially seek out male collaborators in fields where men are a minority, relative to the homophily displayed by women in fields where women are a minority. However, this latter result is only tentatively supported since there are few journals in which most authors are women (\autoref{alpha_gender_ratio}).

We also found that gender homophily was marginally stronger in 2015-2016 relative to 2005-2006. Although this trend might reflect a change in the gender preferences of researchers seeking collaborators over time, there are alternative (and perhaps more likely) explanations. For example, this trend might result from the increasing number of women working in senior positions in STEMM over the past decade [e.g. @Long_2015; @Bendels_2018; @McKenzie_2017]. As shown in \autoref{simulation}, if enough coauthorships are between junior and senior researchers, a large gender gap between career stages can give the appearance of heterophily. As this gender gap between career stages lessens, the observed values of $\alpha$ may increase. 

Our study begs two questions: what causes gender homophily in science, and are our results cause for concern? These questions are closely related. For example, some of the homophily we observed might be caused by women seeking to avoid harassment or sexism from men [@jagsi_2016], which would clearly be concerning. Additionally, Sheltzer and Smith [-@sheltzer_2014] concluded that 'elite' male academics (defined as recipients of major honours) have a higher proportion of male students and postdocs than non-elite male academics. This finding could contribute to the homophily we observed, and is cause for concern since Sheltzer and Smith [-@sheltzer_2014]'s results might reflect discrimination against women during hiring [@Moss_2012], or avoidance by women of elite research groups (e.g. due to 'imposter syndrome' or the perception that these groups are sexist). We also found a little evidence that gender homophily is detrimental to research quality, in that high-impact journals tended to have weaker homophily. Assuming that papers published in high-impact journals are of higher average quality [which is contentious; @Garfield_2006], this result provides non-experimental support for the hypothesis that mixed-gender teams produce better research than single-gender teams [@Britton_2000; @Reagans_2001; @Hong_2004; @Whittington_2008; @Bear_2011; @Herrera_2012; @Campbell_2013].

Homophily might also have more benign causes. Collaboration is often most enjoyable and productive when working with like-minded people, who might be same-gendered more often than not. We also suppose that some people consciously choose to preferentially collaborate with women in order to help close the gender gap in the workforce; this would create homophily if women do this more than men. In support of this interpretation, women appear more likely than men to promote the work of female collagues by inviting them to give talks [@nittrouer_2018; @debarre_2018]. Related to this, Ghiasi et al. [-@Ghiasi_2015] concluded that women in engineering are "compliant [in reproducing] male-dominated scientific structures" because they do not collaborate often enough with other women; their data suggest that coauthorships between two women are about 30% more frequent than expected under random assortment (see their Figure 7). In contrast, we propose that men as well as women should ensure that they are not inadvertently overlooking or excluding female colleagues, particularly since men are disproportionately represented among senior researchers [@Shaw_2012]. 

# Methods
## The dataset
We used the dataset of PubMed author lists from Holman et al. [-@Holman_2018]. Briefly, that dataset was created by downloading every article indexed on PubMed and attempting to infer each author's gender from their given name. Each journal was assigned to one of 107 scientific disciplines, using PubMed's journal categorisations in the interests of objectivity. Because the present study focuses on co-authorship, all single-author papers were discarded. We also discarded all papers for which we could not determine the gender of every author with ${\ge}95\%$ certainty, in order to simplify the statistical analysis. To mitigate Wahlund effects caused by variation in the gender ratio of researchers over time (see below), we also discarded all papers except those that were published either 0-1 or 10-11 years before the PubMed data were collected (i.e. 20^th^ August 2016). Lastly, we excluded journals with fewer than 50 suitable papers. Detailed sample size information is given in S1 Table.

## Calculating $\alpha$, the coefficient of homophily
Following Bergstrom et al. [-@bergstrom_2016], we defined the coefficient of homophily as $\alpha = p - q$, where $p$ is the probability that a randomly-chosen co-author of a _male_ author is a man and $q$ is the probability that a randomly-chosen co-author of a _female_ author is a man. Like the Wahlund effect, $\alpha$ is borrowed from population genetics; for a set of 2-author papers, it is equivalent to Wright's coefficient of inbreeding [@wright_1949]. Mathematical work illustrates that $\alpha$ is closely related to alternative network-based methods for quantifying homophily [@wang_2016].

To estimate $\alpha$ for a particular subset of the scientific literature, we estimated $p$ as the average proportion of men's co-authors who are men (averaged across all papers with at least one man author), and $q$ as the average proportion of women's co-authors who are men (averaged across all papers with at least one woman author). To estimate the 95% confidence intervals on $\alpha$ for a given set of $n$ papers, we sampled $n$ papers with replacement 1000 times, estimated $\alpha$ on each sample, and recorded the 95% quantiles of the resulting 1000 estimates.

As well as calculating $\alpha$ for all authors, we calculated $\alpha$ for first or last authors only. $\alpha$ was again defined as $p - q$, but this time $p$ was estimated as the average proportion of male co-authors on papers with a male first (or last) author, and $q$ was estimated as the average proportion of male co-authors on papers with female first (or last) authors. We did not calculate $\alpha$ for other authorship positions (e.g. second or third authors) because this would necessitate culling the dataset to include only papers with a sufficiently long author list, complicating interpretation of the results.
	
Our test assumes that the expected value of $\alpha$ is zero if authors randomly assort, but for small datasets this assumption is not always true (as pointed out by Carl Bergstrom in a blog post, http://www.eigenfactor.org/gender/assortativity/note_to_eisen.rtf). To borrow Prof. Bergstrom's example, consider a small research specialty comprising just two men and two women researchers, who have together produced six two-author papers: one in each of the six possible two-author combinations. For these six papers, $\alpha = -\frac{1}{3}$, even though same- and opposite-gendered coauthors were selected in equal proportion to their frequency in the pool of possible collaborators. 

To control for the fact that the null expectation for $\alpha$ is not zero for small datasets, we devised an adjusted version of the coefficient of homophily, which we term $\alpha'$. Every time we calculated $\alpha$ for a set of papers, we also determined the expected value of $\alpha$ under the null hypothesis that authors assort randomly with respect to gender. This was accomplished by randomly permuting authors across papers 1000 times, recalculating $\alpha$, and taking the median. We then calculated $\alpha'$ by subtracting the null expectation for $\alpha$ from the observed value. We also used the null-simulated $\alpha$ values to calculate a two-tailed p-value for the observed value of $\alpha$; the p-value was defined as the proportion of null simulations for which $|\alpha_{null}| > |\alpha_{obs}|$. We applied false discovery rate (FDR) correction to each set of p-values to account for multiple testing [@Benjamini_1995].

As expected, $\alpha'$ was usually almost identical to $\alpha$ (S6 Fig), but $\alpha$ was downwardly biased relative to $\alpha'$ for small datasets (S7 Fig). Additionally, the correlation between $\alpha'$ and sample size was negligible ($R^2 < 0.01$), suggesting that our calculation of $\alpha'$ effectively removed the dependence of $\alpha$ on sample size. We therefore used $\alpha'$ in all analyses.

## Minimising the Wahlund effect: research discipline and time period
To minimise bias in $\alpha'$ due to the Wahlund effect, we restricted each set of papers to a single research specialty to the greatest extent allowed by our data. Specifically, we only calculated $\alpha'$ for individual journals, since papers from the same journal typically focus on closely related topics. Although some journals, e.g. _PLoS ONE_, publish research from diverse disciplines with very different author gender ratios [@Holman_2018], calculating $\alpha'$ for these highly multidisciplinary journals is still useful as a contrast. The difference in $\alpha'$ between highly multidisciplinary and more specialised journals, e.g. _PLoS ONE_ versus _PLoS Computational Biology_, gives an estimate of the extent to which multidisciplinarity inflates $\alpha'$.

As well as varying between disciplines, the gender ratio of authors has changed markedly over time [@Holman_2018]. Because the gender ratio was more male-biased in the past, $\alpha'$ would be inflated if we calculated it for a sample of papers published over a long enough time frame. To minimise this effect, we only sampled papers from two one-year periods (namely 2005-6 and 2015-16). The median change per year in % (fe)male authors across journals is below 0.5% [@Holman_2018], and so restricting our dataset to a single year should prevent temporal changes in gender ratio from noticeably affecting our estimates of $\alpha'$. 

## Minimising the Wahlund effect: author country of affiliation
A Wahlund effect could arise even if one calculates $\alpha'$ for a single discipline and time period, because of variation in the gender ratio of researchers from different countries. For example, Holman et al. [-@Holman_2018] showed that PubMed-indexed authors based in Serbia are more than twice as likely to be women as are authors based in Japan. Therefore, a dataset containing a mix of papers from teams of authors based in these two countries would contain an excess of same-sex coauthorships, even if collaboration were random with respect to gender within each country. 
To address this issue, we also analysed every combination of journal and author country of affiliation for which we had enough data (i.e. 50 or more papers published in 2015-16). For simplicity, we restricted the dataset to only include papers for which Holman et al. [-@Holman_2018] had identified the country of affiliation for all authors on the paper, and all authors shared the same country of affiliation. Restricting the dataset in this fashion produced enough data to measure $\alpha'$ for 325 combinations of journal and country (median: 70 papers and 273 authors per combination).

## Calculating standardised journal impact factor
We obtained the 3-year impact factor for each journal from Clarivate Analytics. To account for large differences in impact factor between disciplines, we took the the residuals from a model with $Log_{10}$ impact factor as the response and the research discipline of the journal as a random effect. Thus, journals with a positive standardised impact factor have a higher mean number of citations than the average for journals in their discipline. We then used Spearman rank correlation to test whether $\alpha'$ was correlated with impact factor across journals.

## Statistical analysis
Previous authors [e.g. @sheltzer_2014; @Bonham_2017] have hypothesised that senior scientists preferentially recruit staff and students of the same gender, and/or that junior researchers preferentially select same-gendered mentors. In the majority of PubMed-indexed disciplines, authorship conventions mean that the first-listed author is often an early-career researcher, while the author listed last is more likely to be a senior researcher leading a research team [@Wren_2007]. Assuming that senior researchers are the main drivers of homophily and that there are enough papers with three or more authors, we predict that the last author's gender will be the strongest predictor of the remaining authors' genders (i.e. the gender of the last author will be more salient than that of the first author, or any other authorship position). This is because the first author's gender would simply be an imperfect correlate of the true causal effect, while the last author's gender would be the causal effect itself. 

To test whether $\alpha'$ for last authors tends to be higher than $\alpha'$ for first authors for any given dataset, we used a linear mixed model implemented in the ``lme4`` and ``lmerTest`` packages for R, with _authorship position_ (first or last) as a fixed factor, and _journal_ and _research discipline_ as crossed random effects. The response variable was $\alpha'$, and we weighted each observation by the inverse of the standard error from our estimate of $\alpha'$, meaning that more accurate measurements of $\alpha'$ had more influence on the results. We used a similar model to test for a difference in $\alpha'$ between the 2005-6 and the 2015-16 datasets, with two differences: we fit year range as a two-level fixed factor (instead of authorship position), and we used $\alpha'$ estimated for all authors (not first/last authors) as the response variable.

The relationship between the gender ratio of authors publishing in a journal and its $\alpha'$ value appeared nonlinear (see Results). We therefore fit a generalised additive model with thin plate regression spline smoothing, implemented using the ``mgcv`` package for R.

## Theoretical expectations for $\alpha$ when the gender ratio differs between career stages
In many STEMM subjects, the gender ratio is more skewed among established researchers relative to early-career researchers [@Shaw_2012; @Holman_2018]. We hypothesised that this skew could potentially create both Wahlund effects and 'reverse' Wahlund effects. For example, imagine that the majority of collaborations are between students and professors, and that the gender ratio differs between career stages: we will then see an excess of mixed-gender coauthorships (heterophily, $\alpha < 0$), even if gender has no direct, causal effect. Similarly, a hypothetical field in which students work only with students, and professors with professors, would have apparent gender homophily ($\alpha > 0$).

We can think of no tractable method of controlling for this issue using our dataset, which contains no information on career stage. Therefore, we instead decided to derive the theoretical expectations for $\alpha$ when there is a difference in gender ratio across career stages, in order to determine if and how this effect should alter our inferences. For simplicity, our calculations assume there are only two career stages, though we intuit that the general conclusions would also apply to a multi-tier career ladder. Under the null model that gender has no causal effect on collaboration, we calculated $\alpha$ for various combinations of the four free parameters, i.e. the gender ratios for early- and late-career researchers, and the relative frequency of collaborations between early-early, early-late, and late-late collaborations. We then used the theoretical expectations for $\alpha$ to qualify our main conclusions (see Results). The Online Supplementary Material gives annotated R code used to derive the theoretical expectations.

## Data availability and reproducibility
The Online Supplementary Material contains R scripts used to produce all results, figures and tables. The input data from Holman et al. [-@Holman_2018] is archived at https://osf.io/bt9ya/ along with the code used to obtain it.

# Acknowledgements
CM was supported by the Academy of Finland (284666 to the Centre of Excellence in Biological Interactions).

# References
<div id="refs"></div>

\newpage
# Supporting information
S1 Fig.  There is a very strong correlation between the values of $\alpha$ and $\alpha'$ calculated for each journal, though in a handful of cases the difference is considerable. The deviation between $\alpha$ and $\alpha'$ is greatest for journals for which there is a small sample size (see S2 Fig).

S2 Fig. For journals for which we recovered a small number of papers (<100), the unadjusted metric $\alpha$ was downwardly biased. This fits our expectations: because authors cannot be their own co-authors, small datasets will tend to produce negative estimates of $\alpha$ even if authors assort randomly with respect to gender (see main text). This suggests that $\alpha'$ is a more useful measure of homophily and heterophily, especially for small samples.

S3 Fig. Histogram showing the distribution of differences in $\alpha'$ between the 2015-16 and 2005-6 samples, where positive numbers indicate an increase in $\alpha'$ with time. The mean is slightly positive (namely 0.004), indicating a mild increase in average $\alpha'$ with time.

S4 Fig. Histogram showing the difference between $\alpha'$ calculated for first and last authors. Positive values mean that $\alpha'$ was higher when calculated for first authors, and negative values mean $\alpha'$ was higher when calculated for last authors. The mean is very slightly higher than zero, indicating that $\alpha'$ tends to be higher for first authors.

S5 Fig. Histogram of $\alpha'$ for 325 unique combinations of journal and country, using data from August 2015 - August 2016. The white areas denote combinations for which $\alpha'$ differs significantly from zero (p < 0.05, following false discovery rate correction).
 
S6 Fig. Plot showing the 68 combinations of journal and author country of affiliation for which $\alpha'$ is significantly higher than expected.

S7 Fig. Histogram showing the estimated degree to which $\alpha'$ is inflated by inter-country differences in author gender ratio, across the 285 journals for which we had adequate data after restricting the analysis by country. The average inflation in $\alpha'$ is negligible, suggesting that Wahlund effects resulting from inter-country differences have a neglible effect on our estimates of gender homophily.

S1 Table. Sample sizes for the two datasets, which comprise papers published in the timeframes August 2005 - August 2006, and August 2015 - August 2016.

S2 Table. Number of journals showing statistically significant homophily or heterophily, in two one-year periods. The significance threshold was p < 0.05, and p-values were adjused using Benjamini-Hochberg false discovery rate correction. Note that the power of our test is lower for the 2005-2006 data because fewer papers were recovered per journal: thus, it is not meaningful to compare the % significant journals (i.e. 11% vs 24%) between the two time periods.

S3 Table. The table shows similar information to S3 Fig, namely the distribution of the $\alpha'$ values across journals, split by the research discipline. The gender ratio column shows the percentage of women authors in the sample used to calculate $\alpha'$, across all authorship positions. In the last two columns, the numbers outside parentheses give the number of journals that deviate statistically significantly from zero, while the numbers inside parentheses give the number that remain significant after false discovery rate correction.

S1 Data: This spreadsheet shows the $\alpha$ values calculated for each journal, in the 2005 and 2015 samples, and for each type of author (all authors, first authors, and last authors). The tables gives the impact factor of each journal, the sample size, $\alpha$ and $\alpha'$ and their 95% CIs, and the p-value from a 2-tailed test evaluating the null hypothesis that $\alpha$ is zero (both raw and FDR-corrected p-values are shown).
